# Generated by Django 3.0.6 on 2020-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
