# Generated by Django 3.0.6 on 2020-05-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200506_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
